-- OBSOLETE. Intentionally inert — do not run this file.
--
-- This used to create lowercase plural tables (profiles, missions,
-- user_missions, daily_questions) and attach RLS policies to them. Those tables
-- are not the app's schema: Prisma generates singular quoted names ("User",
-- "Mission", "UserMission", "DailyQuestion"), which is what prisma/schema.prisma
-- declares and what every query in this codebase uses. Nothing references the
-- lowercase tables, so the file created objects no code ever read.
--
-- It was also actively dangerous to keep around. Its "Profiles: auth read"
-- policy granted every authenticated user SELECT on *every* row of profiles,
-- which contains each user's name, image and aura — a PII broadcast — while the
-- comment above it described that as preventing PII exposure. The file's header
-- told readers to paste it into Supabase → SQL Editor, so a setup step that
-- followed it would have deployed that policy.
--
-- Live schema and RLS, in the order that actually applies:
--   1. prisma/schema.prisma        — the source of truth for tables
--   2. prisma/migrations/*         — run via `prisma migrate deploy`; enables RLS
--                                    on every public table and revokes anon/
--                                    authenticated grants
--   3. supabase/enable-rls.sql     — manual equivalent, for when SQL Editor is
--                                    the only option; covers a fixed table list
--                                    but does NOT revoke grants
